Product.create!([
  {first_name: "Taz", last_name: "Abreuhpougnépougné", description: "Taz-Mania ou Le Diable de Tasmanie est une série télévisée d'animation australien en 65 épisodes de 24 minutes créée par Art Vitello, produite par Warner Bros et diffusée entre le 1er septembre 1991 et le 22 mai 1995 dans le bloc de programmation Fox Kids.\r\n\r\nEn France, la série a été diffusé sous le titre Le Diable de Tasmanie, à partir du 12 septembre 19921 dans l'émission Décode pas Bunny, puis en juillet 1993 dans l'émission Canaille Peluche sur Canal+.\r\nRediffusion et diffusion d'épisodes inédits sous le titre Taz-Mania, à partir de septembre 1994 et sur France 3 dans l'émission Télétaz.\r\nEt actuellement diffusé sur la chaine Boing.", picture_url: "http://res.cloudinary.com/benoit/image/upload/v1485262973/lrv39wkfzgbiikpf7ntx.png", for_sale: false, user_id: 1, start_value: nil, max_value: nil, end_bid_date: nil, bid_batch: 0},
  {first_name: "Tom", last_name: "Mo", description: "Il est développeur full-stack junior avec un background en électronique. Fort d'experiences professionnelles transversales et complémentaires, sa rapidité d'adaptation est un atout. Il a une bonne compréhension des enjeux et des problématiques de chacun. Il cherche a sanctionner la fin de sa formation intensive par un défi en informatique embarquée. Et ouais, c'est comme il dit, un kakakakakaaaador.", picture_url: "http://res.cloudinary.com/benoit/image/upload/v1485266231/mqajecxy6oobd87bv3zv.jpg", for_sale: false, user_id: 1, start_value: 10000, max_value: nil, end_bid_date: nil, bid_batch: 0},
  {first_name: "Mickey", last_name: "Mouse", description: "Mickey Mouse est un personnage de fiction appartenant à l'univers Disney, apparaissant principalement dans des dessins animés, dans des bandes dessinées et des jeux vidéo. Véritable ambassadeur de la Walt Disney Company, il est présent dans la plupart des secteurs d'activité de la société, que ce soit l'animation, la télévision, les parcs d'attractions ou les produits de consommation. Mickey est utilisé comme un vecteur de communication et ses qualités doivent respecter la morale prônée par « Disney », que ce soit par Walt ou par l'entreprise elle-même. Mickey Mouse est connu et reconnu dans le monde entier, sa célèbre silhouette formée de trois cercles étant devenue indissociable de la marque Disney.", picture_url: "http://res.cloudinary.com/benoit/image/upload/c_scale,h_800,w_800/v1485258067/pdudmobmdlusvdmgvhfh.png", for_sale: true, user_id: 1, start_value: 10000, max_value: nil, end_bid_date: nil, bid_batch: 0},
  {first_name: "Pancho", last_name: "Villa", description: "José Doroteo Arango Arámbula, plus connu sous le pseudonyme de Francisco Villa et le diminutif Pancho Villa (5 juin 1878 à La Coyotada, non loin de Río Grande à huit kilomètres du village de San Juan del Río, Durango - 20 juillet 1923 à Parral, Chihuahua), est un hors-la-loi mexicain devenu chef de la División del Norte (México) (es) et général de l'armée fédérale au cours de la révolution mexicaine.", picture_url: "http://res.cloudinary.com/benoit/image/upload/v1485265415/sr1qwlwojioz5r2st1nc.jpg", for_sale: false, user_id: 1, start_value: nil, max_value: nil, end_bid_date: nil, bid_batch: 0},
  {first_name: "Babar", last_name: "Le Roi des colons", description: "Cécile de Brunhoff est à l'origine de Babar. Elle a coutume de raconter des histoires à ses deux fils, Laurent et Mathieu. Parmi celles-ci, celle qui décrit les aventures d'un petit éléphant qui s'enfuit à pied de la forêt pour échapper au chasseur et arrive dans une ville où il s'habille comme un homme. Revenu chez lui en voiture, il y rapporte les bénéfices de la civilisation et est couronné roi des éléphants.\r\n\r\nCe récit de leur mère pianiste leur plaît tellement qu'ils le racontent à leur père, Jean de Brunhoff, artiste peintre. L'idée lui vient alors d'en faire un livre illustré pour un usage familial. Son frère Michel de Brunhoff et son beau-frère Lucien Vogel, enthousiasmés, le publient en grand format aux Éditions du Jardin des Modes sous le titre L'Histoire de Babar le petit éléphant (1931), à l'époque de l'Exposition coloniale.\r\n\r\nLes albums connaissent un succès inouï avec quatre millions d'exemplaires vendus avant 1939, après que la maison Hachette a racheté en 1936 les droits aux Editions du Jardin des Modes. Babar rencontre également un grand succès aux États-Unis et en Grande-Bretagne. De 1940 à 1946, Francis Poulenc en réalise une mise en musique pour récitant et piano, plus tard orchestrée par Jean Françaix. À la disparition de son père en 1937, c'est Laurent de Brunhoff qui poursuit les aventures de Babar et les adapte pour la télévision française en 1969.\r\n\r\nLaurent de Brunhoff s'installe en 1985 aux États-Unis et confie en 1987 à la Clifford Ross Company la charge de choisir les sociétés à qui accorder les licences de produits dérivés. La société Nelvana, détenant la franchise au Canada et voulant multiplier ces produits dérivés, entre en conflit avec la Clifford Ross Company, la bataille judiciaire ne s'achevant qu'en 20002.\r\n\r\nLa famille Brunhoff ayant fait don de dessins préparatoires de trois des premiers albums à la Bibliothèque nationale de France, 2006 voit la consécration de Babar en France, avec son entrée dans les collections de cette bibliothèque3.\r\n\r\nEn 2011, 13 millions d'exemplaires des 75 albums sortis ont été vendus dans le monde et traduits en 27 langues.", picture_url: "http://res.cloudinary.com/benoit/image/upload/c_scale,h_800,w_800/v1485263692/yhw1fltkoorkxt6lwf9q.jpg", for_sale: true, user_id: 1, start_value: 500000, max_value: nil, end_bid_date: nil, bid_batch: 0},
  {first_name: "Le", last_name: "Desespéré", description: "Durant les années 1849, Courbet réalise des portraits et essentiellement des autoportraits. Il passe son temps au Louvre à recopier Ribera, Zurbaran, Velasquez, ou Rembrandt qui influencèrent les débuts de son œuvre.\r\n\r\nOn pense que cette peinture a été réalisée peu après son installation à Paris. Elle le montre « désespéré » mais surtout jeune et beau.\r\n\r\nCourbet tenait beaucoup à cette toile puisqu'il l'emmena en exil avec lui en Suisse. Le docteur Paul Collin au chevet de Courbet durant ses derniers jours, décrit l'atelier du peintre et, plus particulièrement, « un tableau représentant Courbet avec une expression désespérée et qu’il avait intitulé pour cette raison Désespoir. ».", picture_url: "http://res.cloudinary.com/benoit/image/upload/v1485525200/kbojpyvmakpn1sf6yvq9.jpg", for_sale: false, user_id: 2, start_value: 1000000, max_value: nil, end_bid_date: nil, bid_batch: 0}
])
Rating.create!([
  {rateable_type: "Product", rateable_id: 2, value: 3, user_id: 1, comment: nil},
  {rateable_type: "Product", rateable_id: 6, value: 3, user_id: 2, comment: nil},
  {rateable_type: "Product", rateable_id: 5, value: 1, user_id: 2, comment: nil},
  {rateable_type: "Product", rateable_id: 3, value: 1, user_id: 2, comment: nil},
  {rateable_type: "Product", rateable_id: 2, value: 3, user_id: 2, comment: nil},
  {rateable_type: "Product", rateable_id: 7, value: 5, user_id: 2, comment: nil},
  {rateable_type: "Product", rateable_id: 3, value: 5, user_id: 1, comment: nil},
  {rateable_type: "Product", rateable_id: 4, value: 5, user_id: 2, comment: nil},
  {rateable_type: "Product", rateable_id: 5, value: 5, user_id: 1, comment: nil},
  {rateable_type: "Product", rateable_id: 6, value: 5, user_id: 1, comment: nil},
  {rateable_type: "Product", rateable_id: 4, value: 4, user_id: 1, comment: nil}
])
